import localFont from "next/font/local";
import type { Metadata } from "next";
import type { WithChildren } from "@/types";
import "@/styles/index.css";
import { SidebarProvider } from "@/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar/AppSidebar";

const syneSans = localFont({
  src: "./fonts/SyneSansVF.ttf",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Phenomenon Next JS Template",
  description: "Generated by create next app",
};

const RootLayout: React.FC<WithChildren<unknown>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${syneSans.className} antialiased`}>
        <main className="h-full">
          <div className="flex gap-8 flex-1">
            <SidebarProvider>
              <AppSidebar />
            </SidebarProvider>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
